USE WORLD;

SELECT NAME FROM CITY;
SELECT NAME FROM CITY ORDER BY NAME DESC;
SELECT DISTINCT NAME FROM CITY;
SELECT NAME FROM CITY WHERE COUNTRYCODE = "CAN";
SELECT NAME FROM CITY WHERE DISTRICT = "Ontario" ORDER BY NAME ASC;

SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = "ARG";
SELECT COUNT(NAME) FROM CITY WHERE COUNTRYCODE = "BEL";
SELECT DISTINCT DISTRICT FROM CITY WHERE COUNTRYCODE = "BRA";
SELECT AVG(POPULATION) FROM CITY WHERE COUNTRYCODE = "BRA";
SELECT COUNT(*) FROM CITY;
