USE WORLD;

-- Part A: Querying the city table --

--A1--
SELECT *
    FROM CITY
    WHERE ID = 31;

--A2--
SELECT NAME
    FROM CITY
    WHERE COUNTRYCODE = 'NLD';

--A3--
SELECT NAME, COUNTRYCODE
    FROM CITY
    WHERE POPULATION > 20000
    ORDER BY POPULATION
    DESC;


-- Part B: Querying the country table--

--B1--
SELECT NAME, REGION, INDEPYEAR, POPULATION
    FROM COUNTRY
    WHERE INDEPYEAR = 1993
        OR (
          INDEPYEAR < 1991 AND POPULATION < 22000000
        );

--B2--
SELECT NAME, INDEPYEAR
    FROM COUNTRY
    WHERE INDEPYEAR > 1960
        AND INDEPYEAR < 1980
    ORDER BY INDEPYEAR;

--B3--
SELECT NAME, CONTINENT
    FROM COUNTRY
    WHERE INDEPYEAR > 1960
        AND INDEPYEAR < 1980
    ORDER BY INDEPYEAR;

--B4--
SELECT NAME, CONTINENT
    FROM COUNTRY
    WHERE CONTINENT = "Europe"
        OR CONTINENT = "North America"
    ORDER BY CONTINENT, NAME;

--B5--
SELECT NAME, CONTINENT
    FROM COUNTRY
    WHERE CONTINENT NOT IN("Europe", "North America")
    ORDER BY CONTINENT, NAME;

--B6--
SELECT NAME, CONTINENT
    FROM COUNTRY
    WHERE CONTINENT LIKE '%America'
    ORDER BY CONTINENT, NAME;

--B7--
SELECT NAME, CONTINENT
    FROM COUNTRY
    WHERE NAME LIKE '_____'
    ORDER BY CONTINENT, NAME;

--B8--
SELECT NAME, CONTINENT
    FROM COUNTRY
    WHERE NAME LIKE '__y__'
    ORDER BY CONTINENT, NAME;

--B9--
SELECT NAME, CONTINENT, INDEPYEAR
    FROM COUNTRY
    WHERE INDEPYEAR IS NULL
    ORDER BY CONTINENT, NAME;

--B10--
SELECT NAME, CONTINENT, INDEPYEAR
    FROM COUNTRY
    WHERE INDEPYEAR IS NOT NULL
    ORDER BY CONTINENT, NAME;

--B11--
SELECT NAME, CONTINENT, INDEPYEAR
    FROM COUNTRY
    WHERE INDEPYEAR IS NOT NULL
    ORDER BY CONTINENT, NAME LIMIT 5;
